---
Name: nextgenimages
After:
  - "silverstripe/framework#*"
  - "silverstripe/assets#assetsimage"
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Assets\Image_Backend:
    class: 'WebbuildersGroup\NextGenImages\NextGenImagesBackend'
    factory: '%$SilverStripe\Assets\ImageBackendFactory'
  SilverStripe\Assets\FilenameParsing\FileResolutionStrategy.public:
    properties:
      ResolutionFileIDHelpers:
        - '%$WebbuildersGroup\NextGenImages\FilenameParsing\HashFileIDHelper'
        - '%$WebbuildersGroup\NextGenImages\FilenameParsing\NaturalFileIDHelper'
  SilverStripe\Assets\FilenameParsing\FileResolutionStrategy.protected:
    properties:
      ResolutionFileIDHelpers:
        - '%$WebbuildersGroup\NextGenImages\FilenameParsing\HashFileIDHelper'
        - '%$WebbuildersGroup\NextGenImages\FilenameParsing\NaturalFileIDHelper'

SilverStripe\Assets\Image:
  extensions:
    - 'WebbuildersGroup\NextGenImages\Extensions\ImageExtension'
