---
Name: nextgenimages
After:
  - "silverstripe/framework#*"
  - "silverstripe/assets#assetsimage"
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Assets\FilenameParsing\FileResolutionStrategy.public:
    properties:
      ResolutionFileIDHelpers:
        - '%$WebbuildersGroup\NextGenImages\FilenameParsing\HashFileIDHelper'
        - '%$WebbuildersGroup\NextGenImages\FilenameParsing\NaturalFileIDHelper'
  SilverStripe\Assets\FilenameParsing\FileResolutionStrategy.protected:
    properties:
      ResolutionFileIDHelpers:
        - '%$WebbuildersGroup\NextGenImages\FilenameParsing\HashFileIDHelper'
        - '%$WebbuildersGroup\NextGenImages\FilenameParsing\NaturalFileIDHelper'

SilverStripe\Assets\File:
  allowed_extensions:
    - 'webp'

SilverStripe\Assets\Image:
  extensions:
    - 'WebbuildersGroup\NextGenImages\Extensions\ImageExtension'

SilverStripe\Assets\Storage\DBFile:
  extensions:
    - 'WebbuildersGroup\NextGenImages\Extensions\ImageExtension'
  supported_images:
    - 'image/webp'
